# Generated by Django 5.0.2 on 2024-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='complemento',
            new_name='complement',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='shifit',
            new_name='shift',
        ),
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
