# Generated by Django 5.0.2 on 2024-04-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='previous_school',
        ),
        migrations.AddField(
            model_name='student',
            name='school_type',
            field=models.CharField(choices=[('Comunitária', 'Comunitária'), ('Municipal', 'Municipal'), ('Estadual', 'Estadual'), ('Federal', 'Federal'), ('Privada', 'Privada'), ('Outra', 'Outra')], default=0, max_length=11),
            preserve_default=False,
        ),
    ]
