# Generated by Django 5.0.2 on 2024-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_shift_alter_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='color_race',
            field=models.CharField(blank=True, choices=[('Mulher', 'Mulher'), ('Homem', 'Homem'), ('Não-binário', 'Não-binário'), ('Gênero Fluído', 'Gênero Fluído'), ('Outro', 'Outro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Cancelado', 'Cancelado'), ('Cancelado', 'Cancelado'), ('Cursando', 'Cursando'), ('Trancado', 'Trancado'), ('Concluído', 'Concluído')], max_length=12),
        ),
    ]
