# Generated by Django 5.0.2 on 2024-04-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_city_region_institute_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('course', 'student')},
        ),
    ]
