# Generated by Django 5.0.2 on 2024-04-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_studentcourse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_type',
            field=models.CharField(choices=[('Comunitária', 'Comunitária'), ('Municipal', 'Municipal'), ('Estadual', 'Estadual'), ('Federal', 'Federal'), ('Privada', 'Privada'), ('Outra', 'Outra')], max_length=30),
        ),
    ]
