# Generated by Django 5.0.2 on 2024-03-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_color_race_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='shift',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Integral', 'Integral')], max_length=16),
        ),
    ]
