# Generated by Django 5.0.2 on 2024-03-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_course_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modality',
            field=models.CharField(choices=[('Presencial', 'Matutino'), ('Híbrido', 'Vespertino'), ('A Distância', 'A Distância')], default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='shift',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Integral', 'Integral')], max_length=12),
        ),
    ]
