# Generated by Django 5.0.2 on 2024-03-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year_created',
            field=models.IntegerField(default=2050),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
